### PR TITLE
Also install buildship.core

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
https://ci.eclipse.org/xtext/job/releng/job/xtext-xtend-api-diff/187/console ran from the forked repo with the fix applied

**Comment by szarnekow** [comment]
I'm not allowed to merge this myself. Please press the button if you find this to be an ok fix. @Hejado @kthoms @cdietrich

**Comment by cdietrich** [comment]
I wonder why will check repo settings

**Comment by cdietrich** [comment]
You are actually member of Xtext dev and should be able to merge

**Review by cdietrich — APPROVED** [review]

**Comment by szarnekow** [comment]
Interesting ... somehow I could not push directly to this repo ... probably used the wrong clone URL. Merged.

**Pull request merged**
