### PR TITLE
Prepare API diff for 2.34

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/releng/job/xtext-api-diff/job/cd_233/ Is red

**Comment by szarnekow** [comment]
> https://ci.eclipse.org/xtext/job/releng/job/xtext-api-diff/job/cd_233/ Is red

How's that one related to this MR?

**Comment by cdietrich** [comment]
I am blind

**Comment by cdietrich** [comment]
Where is the Mr build?

**Comment by cdietrich** [comment]
Looks like Scan repo runs every 100 years only. Triggered it manually

**Comment by cdietrich** [comment]
Mwe url needs to be adjusted too

**Comment by szarnekow** [comment]
> Mwe url needs to be adjusted too

Thanks for the hint. Build is green now.

**Review by cdietrich — APPROVED** [review]

**Pull request merged**
